name: EnchantmentExtractor
version: @VERSION@
description: Extract your beloved enchantments into books!
author: PuppyFirelyte
website: https://github.com/puppyize/EnchantmentExtractor

main: me.puppyize.enchantmentextractor.EnchantmentExtractor
database: false