name: EnchantmentExtractor
version: 1.2.1
description: Extract your beloved enchantments into books!
author: Puppyize
website: https://github.com/puppyize/EnchantmentExtractor

main: me.puppyize.enchantmentextractor.EnchantmentExtractor
database: false